import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const fontGeistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const fontGeistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const Layout = ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  const className = `${fontGeistSans.variable} ${fontGeistMono.variable} antialiased`;
  return (
    <html lang="en">
      <body className={className}>{children}</body>
    </html>
  );
};

export default Layout;
